version: '2'
services:
  nginx:
    image: nginx:1.17.10-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - rails:rails
      - next:next
  next:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  rails:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: vacancy
      POSTGRES_DB: vacancy
      POSTGRES_PASSWORD: youshallnotpass
